### ISSUE TITLE
Infiniband mlx5 NCCL GPU RDMA Distributed Inference Workload not running

### ISSUE THREAD

**Issue by inheaden-admin** [siderolabs/docs#566]
### Description
Hello,
we in the progress of setting up an Inference Cluster with HP ProLiant Nodes where each of the nodes has 8x A100 SXM4 and 4x QLogic mlx5 Infiniband Network Adapters.
We like to run a big model across several nodes. We created the following test workload to check if GPU RDMA is using IB and not IB/NET via Socket Network (which would be slow Ethernet).

We are using hostNetwork and mounting /dev/infiniband into the container to interact with the Infiniband devices.

It would be great to see, if someone did a similar setup and can help ?

Deployment Manifest
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nccl-test-script
  namespace: debug
data:
  test_nccl.py: |
    # Test PyTorch NCCL
    import torch
    import torch.distributed as dist
    dist.init_process_group(backend="nccl")
    local_rank = dist.get_rank() % torch.cuda.device_count()
    torch.cuda.set_device(local_rank)
    data = torch.FloatTensor([1,] * 128).to("cuda")
    dist.all_reduce(data, op=dist.ReduceOp.SUM)
    torch.cuda.synchronize()
    value = data.mean().item()
    world_size = dist.get_world_size()
    assert value == world_size, f"Expected {world_size}, got {value}"

    print("PyTorch NCCL is successful!")

    # Test PyTorch GLOO
    gloo_group = dist.new_group(ranks=list(range(world_size)), backend="gloo")
    cpu_data = torch.FloatTensor([1,] * 128)
    dist.all_reduce(cpu_data, op=dist.ReduceOp.SUM, group=gloo_group)
    value = cpu_data.mean().item()
    assert value == world_size, f"Expected {world_size}, got {value}"

    print("PyTorch GLOO is successful!")

    if world_size <= 1:
        exit()

    # Test vLLM NCCL, with cuda graph
    from vllm.distributed.device_communicators.pynccl import PyNcclCommunicator

    pynccl = PyNcclCommunicator(group=gloo_group, device=local_rank)
    pynccl.disabled = False

    s = torch.cuda.Stream()
    with torch.cuda.stream(s):
        data.fill_(1)
        out = pynccl.all_reduce(data, stream=s)
        value = out.mean().item()
        assert value == world_size, f"Expected {world_size}, got {value}"

    print("vLLM NCCL is successful!")

    g = torch.cuda.CUDAGraph()
    with torch.cuda.graph(cuda_graph=g, stream=s):
        out = pynccl.all_reduce(data, stream=torch.cuda.current_stream())

    data.fill_(1)
    g.replay()
    torch.cuda.current_stream().synchronize()
    value = out.mean().item()
    assert value == world_size, f"Expected {world_size}, got {value}"

    print("vLLM NCCL with cuda graph is successful!")

    dist.destroy_process_group(gloo_group)
    dist.destroy_process_group()
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nccl-config
  namespace: debug
data:
  OMP_NUM_THREADS: "1"
  NCCL_DEBUG: "TRACE"
  NCCL_DEBUG_SUBSYS: "INIT,NET,ENV"
  NCCL_IB_GID_INDEX: "3"
  NCCL_IB_HCA: "mlx5"
  NCCL_SOCKET_IFNAME: "ibs17"
  NCCL_IB_DISABLE: "0"
  GLOO_SOCKET_IFNAME: "ibs17"
---
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: nccl-test
  namespace: debug
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        hostNetwork: true
        hostIPC: true
        dnsPolicy: ClusterFirstWithHostNet
        nodeSelector:
          kubernetes.io/hostname: "cn76"
        runtimeClassName: nvidia
        tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "present"
          effect: "NoSchedule"
        containers:
          - name: nccl-test-leader
            image: vllm/vllm-openai:v0.20.2
            envFrom:
              - configMapRef:
                  name: nccl-config
            command:
              - /bin/sh
              - -c
              - >
                torchrun
                --nnodes=2
                --nproc_per_node=8
                --rdzv_id=nccl-test
                --rdzv_backend=c10d
                --rdzv_endpoint=$(LWS_LEADER_ADDRESS):20000
                /mnt/scripts/test_nccl.py
            securityContext:
              capabilities:
                add: [ "IPC_LOCK", "CAP_SYS_ADMIN" ]
            resources:
              requests:
                cpu: "4"
                memory: "32Gi"
                nvidia.com/gpu: "8"
              limits:
                cpu: "4"
                memory: "32Gi"
                nvidia.com/gpu: "8"
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - name: scripts
                mountPath: /mnt/scripts
              - name: infiniband
                mountPath: /dev/infiniband
              - name: ib-sys
                mountPath: /sys/class/infiniband
                readOnly: true
              - name: ib-sys-devices
                mountPath: /sys/devices
                readOnly: true
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          - name: scripts
            configMap:
              name: nccl-test-script
          - name: infiniband
            hostPath:
              path: /dev/infiniband
              type: Directory
          - name: ib-sys
            hostPath:
              path: /sys/class/infiniband
          - name: ib-sys-devices
            hostPath:
              path: /sys/devices
    workerTemplate:
      spec:
        nodeSelector:
          kubernetes.io/hostname: "cn77"
        runtimeClassName: nvidia
        hostNetwork: true
        hostIPC: true
        dnsPolicy: ClusterFirstWithHostNet
        tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "present"
          effect: "NoSchedule"
        containers:
          - name: nccl-test-worker
            image: vllm/vllm-openai:v0.20.2
            envFrom:
              - configMapRef:
                  name: nccl-config
            command:
              - /bin/sh
              - -c
              - >
                torchrun
                --nnodes=2
                --nproc_per_node=8
                --rdzv_id=nccl-test
                --rdzv_backend=c10d
                --rdzv_endpoint=$(LWS_LEADER_ADDRESS):20000
                /mnt/scripts/test_nccl.py
            securityContext:
              capabilities:
                add: [ "IPC_LOCK", "CAP_SYS_ADMIN" ]
            resources:
              requests:
                cpu: "4"
                memory: "32Gi"
                nvidia.com/gpu: "8"
              limits:
                cpu: "4"
                memory: "32Gi"
                nvidia.com/gpu: "8"
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - name: scripts
                mountPath: /mnt/scripts
              - name: infiniband
                mountPath: /dev/infiniband
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          - name: scripts
            configMap:
              name: nccl-test-script
          - name: infiniband
            hostPath:
              path: /dev/infiniband
              type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nccl-test-leader
  namespace: debug
spec:
  ports:
    - name: http
      port: 20000
      protocol: TCP
      targetPort: 20000
  selector:
    leaderworkerset.sigs.k8s.io/name: nccl-test
    role: leader
  type: ClusterIP

```

### Logs

Expectation in the logs is the following:

```
nccl-test:179:179 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB [3]mlx5_3:1/IB [RO]; OOB eth0:10.0.0.1<0>
nccl-test:179:179 [0] NCCL INFO Using network IB  # ← KEY LINE!
nccl-test:179:179 [0] NCCL INFO NCCL_IB_HCA set to mlx5_0,mlx5_1,mlx5_2,mlx5_3
nccl-test:179:179 [0] NCCL INFO Channel 00/0 : 0[0] -> 8[0] [send] via NET/IB/0/GDRDMA  # ← IB + GPUDirect!
nccl-test:179:179 [0] NCCL INFO Channel 00/0 : 8[0] -> 0[0] [receive] via NET/IB/0/GDRDMA
```

Actual Logs of the LWS Pod where it fails:
```
cn76:155:155 [5] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:155:155 [5] NCCL INFO NCCL_SOCKET_IFNAME set to ibs17
cn76:155:155 [5] NCCL INFO NCCL version 2.28.9+cuda13.0
cn76:155:155 [5] NCCL INFO Comm config Blocking set to 1
cn76:154:154 [4] NCCL INFO ENV/Plugin: Could not find: libnccl-env.so
cn76:154:154 [4] NCCL INFO cudaDriverVersion 13000
cn76:154:154 [4] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:154:154 [4] NCCL INFO NCCL_SOCKET_IFNAME set to ibs17
cn76:154:154 [4] NCCL INFO NCCL version 2.28.9+cuda13.0
cn76:154:154 [4] NCCL INFO Comm config Blocking set to 1
cn76:157:157 [7] NCCL INFO ENV/Plugin: Could not find: libnccl-env.so
cn76:157:157 [7] NCCL INFO cudaDriverVersion 13000
cn76:157:157 [7] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:157:157 [7] NCCL INFO NCCL_SOCKET_IFNAME set to ibs17
cn76:157:157 [7] NCCL INFO NCCL version 2.28.9+cuda13.0
cn76:157:157 [7] NCCL INFO Comm config Blocking set to 1
cn76:156:156 [6] NCCL INFO NET/Plugin: Could not find: libnccl-net.so
cn76:156:156 [6] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
cn76:156:156 [6] NCCL INFO dlvsym failed on mlx5dv_get_data_direct_sysfs_path - /lib/x86_64-linux-gnu/libmlx5.so: undefined symbol: mlx5dv_get_data_direct_sysfs_path, version MLX5_1.25 version MLX5_1.25
cn76:156:156 [6] NCCL INFO dlvsym failed on mlx5dv_reg_dmabuf_mr - /lib/x86_64-linux-gnu/libmlx5.so: undefined symbol: mlx5dv_reg_dmabuf_mr, version MLX5_1.25 version MLX5_1.25
cn76:156:156 [6] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:156:156 [6] NCCL INFO NCCL_IB_HCA set to mlx5

[2026-05-15 11:40:19] cn76:156:156 [6] misc/ibvwrap.cc:127 NCCL WARN Call to ibv_open_device failed

[2026-05-15 11:40:19] cn76:156:156 [6] transport/net_ib.cc:715 NCCL WARN NET/IB : Unable to open device mlx5_0

[2026-05-15 11:40:19] cn76:156:156 [6] misc/ibvwrap.cc:127 NCCL WARN Call to ibv_open_device failed

[2026-05-15 11:40:19] cn76:156:156 [6] transport/net_ib.cc:715 NCCL WARN NET/IB : Unable to open device mlx5_1

[2026-05-15 11:40:19] cn76:156:156 [6] misc/ibvwrap.cc:127 NCCL WARN Call to ibv_open_device failed

[2026-05-15 11:40:19] cn76:156:156 [6] transport/net_ib.cc:715 NCCL WARN NET/IB : Unable to open device mlx5_2

[2026-05-15 11:40:19] cn76:156:156 [6] misc/ibvwrap.cc:127 NCCL WARN Call to ibv_open_device failed

[2026-05-15 11:40:19] cn76:156:156 [6] transport/net_ib.cc:715 NCCL WARN NET/IB : Unable to open device mlx5_3
cn76:156:156 [6] NCCL INFO NET/IB : No device found.
cn76:156:156 [6] NCCL INFO NET/IB : Using [RO]; OOB ibs17:10.148.92.116<0>
cn76:156:156 [6] NCCL INFO Failed to initialize NET plugin IB
cn76:156:156 [6] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:156:156 [6] NCCL INFO NET/Socket : Using [0]ibs17:10.148.92.116<0>
cn76:156:156 [6] NCCL INFO Initialized NET plugin Socket
cn76:156:156 [6] NCCL INFO Assigned NET plugin Socket to comm
cn76:156:156 [6] NCCL INFO Using network Socket
```

We conducted a deep debugging of several components:

Kernel Logs / Drivers:
```
kern:    info: [2026-05-15T09:07:31.78924777Z]: mlx5_core 0000:45:00.0: firmware version: 20.29.1016
 SUBSYSTEM=pci
 DEVICE=+pci:0000:45:00.0
info: [2026-05-15T09:07:31.79632511Z]: mlx5_core 0000:45:00.0: 252.048 Gb/s available PCIe bandwidth (16.0 GT/s PCIe x16 link)
 SUBSYSTEM=pci
 DEVICE=+pci:0000:45:00.0
kern:    info: [2026-05-15T09:07:54.542293779Z]: mlx5_core 0000:45:00.0 mlx5_0: Port: 1 Link INIT
 SUBSYSTEM=pci
 DEVICE=+pci:0000:45:00.0
kern:    info: [2026-05-15T09:07:54.575952823Z]: mlx5_core 0000:45:00.0 mlx5_0: Port: 1 Link ACTIVE
```
=> Looks good !

talosctl get addresses:

```
192.168.11.116   network     AddressStatus   ibs17/10.148.92.116/24                         1         10.148.92.116/24               ibs17
192.168.11.116   network     AddressStatus   ibs17/fe80::8ae9:a4ff:ff8d:adde/64             2         fe80::8ae9:a4ff:ff8d:adde/64   ibs17
192.168.11.116   network     AddressStatus   ibs18/fe80::8ae9:a4ff:ffa7:46e6/64             2         fe80::8ae9:a4ff:ffa7:46e6/64   ibs18
192.168.11.116   network     AddressStatus   ibs19/fe80::8ae9:a4ff:ff8d:dcda/64             2         fe80::8ae9:a4ff:ff8d:dcda/64   ibs19
192.168.11.116   network     AddressStatus   ibs20/fe80::8ae9:a4ff:ff8d:bdce/64             2         fe80::8ae9:a4ff:ff8d:bdce/64   ibs20
```
=> Looks also good, the interfaces are detected.

We started a debugging daemonset in k8s with the following parameters:
```
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        - operator: Exists
      containers:
        - name: netshoot
          image: mellanox/mofed:23.10-1.1.9.0-ubuntu22.04-amd64
          command: ["sleep", "infinity"]
          tty: true
          stdin: true
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "IPC_LOCK", "SYS_ADMIN"]
          volumeMounts:
            - name: infiniband
              mountPath: /dev/infiniband
      volumes:
        - name: infiniband
          hostPath:
            path: /dev/infiniband
            type: Directory
```

Inside the container we debugged with the following commands:

```
CMD: ls -la /dev/infiniband/
---
drwxr-xr-x    4 root     root           160 May 15 11:49 .
drwxr-xr-x   16 root     root          3640 May 15 12:06 ..
drwxr-xr-x    2 root     root           120 May 15 11:49 by-ibdev
drwxr-xr-x    2 root     root           120 May 15 11:49 by-path
crw-rw-rw-    1 root     root      231, 192 May 15 11:49 uverbs0
crw-rw-rw-    1 root     root      231, 193 May 15 11:49 uverbs1
crw-rw-rw-    1 root     root      231, 194 May 15 11:49 uverbs2
crw-rw-rw-    1 root     root      231, 195 May 15 11:49 uverbs3
# => Looks good
CMD:i bv_devices
---
    device                 node GUID
    ------              ----------------
    mlx5_0              88e9a4ffffa746e6
    mlx5_1              88e9a4ffff8dadde
    mlx5_2              88e9a4ffff8dbdce
    mlx5_3              88e9a4ffff8ddcda

# => Looks good
CMD: ibv_devinfo -d mlx5_0 # other are the same, all up and working.
---
hca_id: mlx5_0
        transport:                      InfiniBand (0)
        fw_ver:                         20.29.1016
        node_guid:                      88e9:a4ff:ffa7:46e6
        sys_image_guid:                 88e9:a4ff:ffa7:46e6
        vendor_id:                      0x02c9
        vendor_part_id:                 4123
        hw_ver:                         0x0
        board_id:                       MT_0000000451
        phys_port_cnt:                  1
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             4096 (5)
                        sm_lid:                 1
                        port_lid:               366
                        port_lmc:               0x00
                        link_layer:             InfiniBand
# => Looks good
CMD: for d in mlx5_{0..3}; do echo "$d: $(cat /sys/class/infiniband/$d/ports/1/state)"; done
---
mlx5_0: 4: ACTIVE
mlx5_1: 4: ACTIVE
mlx5_2: 4: ACTIVE
mlx5_3: 4: ACTIVE
# => Looks good
```

### Environment

- Talos version: v13.2
systemExtensions:
        officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/bnx2-bnx2x
            - siderolabs/intel-ucode
            - siderolabs/iscsi-tools
            - siderolabs/nvidia-container-toolkit-lts
            - siderolabs/nvidia-fabricmanager-lts
            - siderolabs/nvidia-gdrdrv-device
            - siderolabs/nvidia-open-gpu-kernel-modules-lts
            - siderolabs/nvme-cli
            - siderolabs/qlogic-firmware
            - siderolabs/util-linux-tools

Kernel Modules:
  kernel:
    modules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
      - name: nvme_tcp

- Kubernetes version: 1.36
- Platform: amd64, baremetal

**Comment by inheaden-admin** [comment]
We solved the issue with the following approach:

**a) Load the gdrdrv device Kernel modules according to:
https://github.com/siderolabs/extensions/tree/main/nvidia-gpu/nvidia-gdrdrv-device**

```
machine:
  kernel:
    modules:
      - name: gdrdrv
        parameters:
          - dbg_enabled=0
          - info_enabled=0
          - use_persistent_mapping=1
```

**b) Mount /dev/gdrdrv into the pod**
```
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - name: model-storage
                mountPath: /mnt/llm-models
              - name: infiniband
                mountPath: /dev/infiniband
              - name: gdrdrv
                mountPath: /dev/gdrdrv  # GPU memory access
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: infiniband
          hostPath:
            path: /dev/infiniband
            type: Directory
```

**Result**

```
cn76:154:154 [5] NCCL INFO Connected to proxy localRank 5 -> connection 0x7f4d90006500
cn76:154:154 [5] NCCL INFO Channel 23/0 : 5[5] -> 0[0] via P2P/CUMEM/read
cn76:154:385 [5] NCCL INFO New proxy send connection 47 from local rank 5, transport 0
cn76:154:154 [5] NCCL INFO Connected to proxy localRank 5 -> connection 0x7f4d90006578
cn76:154:385 [5] NCCL INFO New proxy send connection 48 from local rank 4, transport 0
cn76:154:154 [5] NCCL INFO Connected to proxy localRank 4 -> connection 0x7efebc0065f0
cn76:154:154 [5] NCCL INFO Connected to proxy localRank 0 -> connection 0x7f9c2c006668
cn76:154:385 [5] NCCL INFO New proxy send connection 49 from local rank 0, transport 0
cn76:154:154 [5] NCCL INFO Connected all rings, use ring PXN 0 GDR 1
cn76:154:154 [5] NCCL INFO Initialized NET plugin IB
cn76:154:154 [5] NCCL INFO Assigned NET plugin IB to comm
cn76:154:154 [5] NCCL INFO Assigned GIN plugin GIN_IB_GDAKI to comm
cn76:154:154 [5] NCCL INFO Using network IB
cn76:154:154 [5] NCCL INFO DMA-BUF is available on GPU device 5
cn76:154:154 [5] NCCL INFO ncclCommInitRank comm 0x55ec6e806950 rank 0 nranks 2 cudaDev 5 nvmlDev 5 busId 8b000 commId 0xac211f8337a54293 - Init START
cn76:154:154 [5] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 0 'mlx5_0'
cn76:154:154 [5] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 1 'mlx5_1'
cn76:154:154 [5] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 2 'mlx5_2'
cn76:154:154 [5] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 3 'mlx5_3'
cn76:154:154 [5] NCCL INFO GPU Direct RDMA Enabled for GPU 0 / HCA 3 (distance 5 <= 5), read 0 mode Default
cn76:154:154 [5] NCCL INFO GPU Direct RDMA Enabled for GPU 0 / HCA 3 (distance 5 <= 5), read 0 mode Default
cn76:154:154 [5] NCCL INFO ncclTopoGetCpuAffinity: Affinity for GPU 5 is 28-31. (GPU affinity = 28-31 ; CPU affinity = 0-31).
cn76:154:154 [5] NCCL INFO comm 0x55ec6e806950 rank 0 nRanks 2 nNodes 2 localRanks 1 localRank 0 MNNVL 0
cn76:154:154 [5] NCCL INFO Channel 00/02 : 0 1
cn76:154:154 [5] NCCL INFO Channel 01/02 : 0 1
cn76:154:154 [5] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
cn76:154:154 [5] NCCL INFO P2P Chunksize set to 131072
cn76:154:154 [5] NCCL INFO Check P2P Type isAllDirectP2p 1 directMode 0 isAllCudaP2p 1
cn76:154:557 [0] NCCL INFO [Proxy Service] Device 5 CPU core 30
cn76:154:154 [5] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
cn76:154:154 [5] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
cn76:154:154 [5] NCCL INFO CC Off, workFifoBytes 1048576
cn76:154:558 [0] NCCL INFO [Proxy Service UDS] Device 5 CPU core 29
cn76:154:154 [5] NCCL INFO ncclCommInitRank comm 0x55ec6e806950 rank 0 nranks 2 cudaDev 5 nvmlDev 5 busId 8b000 commId 0xac211f8337a54293 - Init COMPLETE
cn76:154:154 [5] NCCL INFO Init timings - ncclCommInitRank: rank 0 nranks 2 total 0.04 (kernels 0.00, alloc 0.00, bootstrap 0.00, allgathers 0.01, topo 0.02, graphs 0.00, connections 0.00, rest 0.00)
cn76:154:154 [5] NCCL INFO GPU Direct RDMA Enabled for GPU 0 / HCA 3 (distance 5 <= 5), read 0 mode Default
cn76:154:557 [5] NCCL INFO New proxy recv connection 0 from local rank 0, transport 2(Worker pid=149) INFO 05-16 10:31:52 [parallel_state.py:1715] rank 0 in world size 16 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
```

**Comment by frezbo** [comment]
@Iheanacho-ai worth documenting
